### ISSUE TITLE
Make filterbank_hilbert function in-house

### ISSUE THREAD

**Issue by rayarxti** [coganlab/IEEG_Pipelines#96]

**Comment by Aaronearlerichardson** [comment]
naplib function can be found here:
https://github.com/naplab/naplib-python/blob/c8fb1feeedd699db28a924eccee4de2aeeec6f6d/naplib/preprocessing/filter_hilbert.py#L267C10-L267C10

**Comment by Aaronearlerichardson** [comment]
closed with #101
